version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-ddbb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=backoffice-backend-dev
    ports:
      - '5433:5432'
    restart: always
  rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: rabbitmq-service
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=p@ssw0rd 
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always